name: Scheduled Newman Regression Test Flow

on:
    workflow_dispatch:
      
jobs:
  collection_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-postman-cloud
          npm install -g newman-reporter-htmlextra

      - name: Run Newman Script (Alternative)
        env:
          #BinBin API Gateway
          COLLECTION_ID: ${{ secrets.BINBINAPIGW_COLLECTION_ID }}
          ENVIRONMENT_ID: ${{ secrets.BINBINAPIGW_TEST_ENVIRONMENT_ID }}
          WORKSPACE_ID: ${{ secrets.BINBINAPIGW_WORKSPACE_ID }}
          POSTMAN_API_TOKEN: ${{ secrets.BINBINAPIGW_API_TOKEN }}

        run: |
          cd workflow_scripts/cronjob
          chmod +x newman.sh
          ./newman.sh "$COLLECTION_ID" "$ENVIRONMENT_ID" "$WORKSPACE_ID" "$POSTMAN_API_TOKEN"

      - name: Recording Newman HTML Test Report
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with: 
          name: Newman HTML Test Report
          path: testResults
  
      - name: Extracting Results for the Google Chat Notification
        run: |
          pwd
          cd workflow_scripts/cronjob
          echo "Running report_helper.js script..."
          node ./report_helper.js

      - name: Setting Extracted Results as Environment Variables
        run: |
          pwd
          chmod +x extracted_results.txt
          cat extracted_results.txt >> $GITHUB_ENV

      - name: Sending Google Chat Notification
        env: 
          NEWMAN_HTML_REPORT_BUTTON_LINK: ${{ steps.artifact-upload-step.outputs.artifact-url }}
          POSTMAN_CLOUD_REPORT_BUTTON_LINK: ${{ env.POSTMAN_CLOUD_REPORT_BUTTON_LINK }}
          GOOGLE_CHAT_URL: ${{ secrets.SCHEDULED_GOOGLE_CHAT_BINBIN_TEST_URL }}
        run: |
          pwd
          cd workflow_scripts/cronjob
          chmod +x notifier.sh
          ./notifier.sh "$GOOGLE_CHAT_URL"