name: Central Newman Regression Test Flow

on:
    workflow_dispatch:
      
jobs:
  collection_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-postman-cloud
          npm install -g newman-reporter-htmlextra

      - name: Run Newman Script (Alternative)
        env:
          #Source Workflow Client Payload
          STATUS: ${{ github.event.client_payload.status }}
          WORKFLOW: ${{ github.event.client_payload.workflow }}
          BRANCH: ${{ github.event.client_payload.branch }}
          REPO: ${{ github.event.client_payload.repo }}
          ARTIFACT: ${{ github.event.client_payload.artifact }} 
          
          #BinBin API Gateway
          BINBINAPIGW_COLLECTION_ID: ${{ secrets.BINBINAPIGW_COLLECTION_ID }}
          BINBINAPIGW_TEST_ENVIRONMENT_ID: ${{ secrets.BINBINAPIGW_TEST_ENVIRONMENT_ID }}
          BINBINAPIGW_WORKSPACE_ID: ${{ secrets.BINBINAPIGW_WORKSPACE_ID }}
          BINBINAPIGW_API_TOKEN: ${{ secrets.BINBINAPIGW_API_TOKEN }}

          #Algoritma TOMP API
          TOMP_COLLECTION_ID: ${{ secrets.TOMP_COLLECTION_ID }}
          TOMP_TEST_ENVIRONMENT_ID: ${{ secrets.TOMP_TEST_ENVIRONMENT_ID }}
          TOMP_WORKSPACE_ID: ${{ secrets.TOMP_WORKSPACE_ID }}
          TOMP_API_TOKEN: ${{ secrets.TOMP_API_TOKEN }}

        run: |
          chmod +x newman.sh
          ./newman.sh "succeed" "test" "test" "binbin-api-gateway" "artifact" "$BINBINAPIGW_COLLECTION_ID" "$BINBINAPIGW_TEST_ENVIRONMENT_ID" "$BINBINAPIGW_WORKSPACE_ID" "$BINBINAPIGW_API_TOKEN" "$TOMP_COLLECTION_ID" "$TOMP_TEST_ENVIRONMENT_ID" "$TOMP_WORKSPACE_ID" "$TOMP_API_TOKEN"

      - name: Recording Newman HTML Test Report
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with: 
          name: Newman HTML Test Report
          path: testResults
  
      - name: Extracting Results for the Google Chat Notification
        run: |
          echo "Running report_helper.js script..."
          node ./report_helper.js

      - name: Setting Extracted Results as Environment Variables
        run: |
          chmod +x extracted_results.txt
          cat extracted_results.txt >> $GITHUB_ENV

      - name: Sending Google Chat Notification
        env: 
          NEWMAN_HTML_REPORT_BUTTON_LINK: ${{ steps.artifact-upload-step.outputs.artifact-url }}
          POSTMAN_CLOUD_REPORT_BUTTON_LINK: ${{ env.POSTMAN_CLOUD_REPORT_BUTTON_LINK }}
          GOOGLE_CHAT_BINBIN_TEST_URL: ${{ secrets.GOOGLE_CHAT_BINBIN_TEST_URL }}
          GOOGLE_CHAT_BINBIN_PROD_URL: ${{ secrets.GOOGLE_CHAT_BINBIN_PROD_URL }}
          GOOGLE_CHAT_ALGORITMA_TEST_URL: ${{ secrets.GOOGLE_CHAT_ALGORITMA_TEST_URL }}
          GOOGLE_CHAT_ALGORITMA_PROD_URL: ${{ secrets.GOOGLE_CHAT_ALGORITMA_PROD_URL }}
          WORKFLOW: ${{ github.event.client_payload.workflow }}
          REPO: ${{ github.event.client_payload.repo }}
        run: |
          chmod +x notifier.sh
          ./notifier.sh "test" "binbin-api-gateway" "arti" "$GOOGLE_CHAT_BINBIN_TEST_URL" "$GOOGLE_CHAT_BINBIN_PROD_URL" "$GOOGLE_CHAT_ALGORITMA_TEST_URL" "$GOOGLE_CHAT_ALGORITMA_PROD_URL"